### ISSUE TITLE
Moving by predefined weaypoints

### ISSUE THREAD

**Issue by linuxenko** [mikolalysenko/l1-path-finder#4]
First of all sorry , my question does not directly related to the path-finder :$

Can you please help me understand, find tools or documentation how to make some movement by predefined maps, how to create them, best practices idk. I'm trying learn through source code of some "towerdefence" games published on github, but.. it looks like they are does not implement it right . I don't know, but it feels like they are trying invent from 0 something like good known and many years available allgorithm. It looks like you know the secret of right algorithm for waypoints (2d of source), can you please help me, or suggest something to read to understand how to do it in right way. 

Thank you

**Comment by mikolalysenko** [comment]
For a tower defense game you might want to consider using Dijkstra's algorithm to compute all single source shortest paths, then have each unit follow along the path tree to get to the root node.  If you precalculate this data once, then you can just store it and get the movement for each unit in O(1) time.

**Comment by linuxenko** [comment]
Thank you !

**Comment by redblobgames** [comment]
And if you don't have different movement costs for edges, you can use Breadth First Search instead of Dijkstra's Algorithm. Demo: http://www.redblobgames.com/pathfinding/tower-defense/

**Comment by linuxenko** [comment]
Thank you @redblobgames ! bfs looks simple,  i'll try implement it. What the better way to visualize it ?
